# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"
    rust: "1.70"

python:
  install:
    - method: pip
      path: reductionml-python/
    - method: pip
      path: utils/reductionml-docs-extension/

conda:
  environment: docs/environment.yml
