[book]
authors = ["Jack Gerrits"]
language = "en"
multilingual = false
src = "src"
title = "reductionml"

[preprocessor.reduction-config-json]
command = "cargo run --manifest-path=./Cargo.toml --bin mdbook-reduction-config"
