name: Check

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: cargo fmt --check
      # Check docs builds
      - run: mdbook build book
      # Includes integration tests which are ignored by default
      - run: cargo test -- --include-ignored
