name: Update pages

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          mkdir -p static/schema
          cargo run -- gen-schema > static/schema/config_schema.json

      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: |
          mdbook build book
          mkdir -p static
          cp -r book/book static/book

      - uses: actions/upload-pages-artifact@v1
        with:
          path: static/
      - id: deployment
        uses: actions/deploy-pages@v2
